import fs from 'node:fs';import path from 'node:path';import {execFileSync} from 'node:child_process';import {candidate,DISCOVERY_SCHEMA,mergeCandidates} from './model.js';import {parseRoots,walk} from './paths.js';
const exists=p=>{try{return fs.existsSync(p)}catch{return false}};
const readJson=p=>{try{return JSON.parse(fs.readFileSync(p,'utf8'))}catch{return null}};
const command=name=>{try{return execFileSync('sh',['-lc',`command -v ${name}`],{encoding:'utf8',timeout:1500}).trim()}catch{return''}};
function scanTree(roots) {
  const items=[],gitRoots=new Set(),backupRoots=new Set(),databaseFiles=[];
  for(const root of roots) {
    walk(root,{maxDepth:5,maxEntries:50000,onEntry(full,stat,depth){
      const name=path.basename(full);
      if(stat.isDirectory()&&exists(path.join(full,'.git'))) {
        gitRoots.add(full);const pkg=readJson(path.join(full,'package.json'));
        const markers=[['package.json',exists(path.join(full,'package.json'))],['pyproject.toml',exists(path.join(full,'pyproject.toml'))],['go.mod',exists(path.join(full,'go.mod'))],['compose',exists(path.join(full,'compose.yml'))||exists(path.join(full,'docker-compose.yml'))]];
        const reasons=['git repository',...markers.filter(x=>x[1]).map(x=>x[0])];
        items.push(candidate({type:'project',key:full,name:pkg?.name||name,path:full,source:'filesystem',confidence:Math.min(.98,.72+reasons.length*.06),reasons,meta:{language:pkg?'node':markers[1][1]?'python':markers[2][1]?'go':'unknown',hasCompose:markers[3][1]}}));
      }
      if(stat.isDirectory()&&/(^|[-_.])(backup|backups|archive|archives|dump|dumps)([-_.]|$)/i.test(name)&&depth>0) {backupRoots.add(full);items.push(candidate({type:'backup',key:full,name,path:full,source:'filesystem',confidence:.78,reasons:['backup-like directory name'],defaultEnabled:true}));}
      if(stat.isFile()&&/\.(sqlite|sqlite3|db)$/i.test(name)&&stat.size>0&&databaseFiles.length<200) {databaseFiles.push(full);items.push(candidate({type:'database',key:full,name,path:full,source:'filesystem',confidence:.66,reasons:['database file extension'],meta:{bytes:stat.size},defaultEnabled:false}));}
    }});
  }
  return{items,gitRoots:[...gitRoots],backupRoots:[...backupRoots],databaseFiles};
}

function scanNginx(){const dir=process.env.NGINX_SITES||'/etc/nginx/sites-enabled',items=[];if(!exists(dir))return items;for(const file of fs.readdirSync(dir)){let text='';try{text=fs.readFileSync(path.join(dir,file),'utf8')}catch{continue}for(const match of text.matchAll(/^\s*server_name\s+([^;]+);/gm))for(const domain of match[1].trim().split(/\s+/))if(/^[a-z0-9.-]+\.[a-z]{2,}$/i.test(domain)&&!domain.startsWith('_'))items.push(candidate({type:'domain',key:domain,name:domain,source:'nginx',confidence:.96,reasons:['active nginx server_name'],meta:{config:file}}))}return items}
function scanSystemd(){const items=[];try{const out=execFileSync('systemctl',['list-unit-files','--type=service','--state=enabled','--no-legend','--no-pager'],{encoding:'utf8',timeout:6000,maxBuffer:1024*1024});for(const line of out.split('\n')){const unit=line.trim().split(/\s+/)[0];if(!unit||/^(systemd-|dbus|apt-|getty@|cron|ssh|nginx|docker|containerd)/.test(unit))continue;items.push(candidate({type:'service',key:unit,name:unit,source:'systemd',confidence:.88,reasons:['enabled systemd service'],meta:{unit}}))}}catch{}return items}
function scanCapabilities(){const specs=[['docker','capability'],['podman','capability'],['pm2','capability'],['nginx','capability'],['apache2','capability'],['caddy','capability'],['certbot','capability'],['fail2ban-client','capability'],['node','runtime'],['python3','runtime'],['php','runtime'],['java','runtime'],['go','runtime'],['postgres','database'],['mysql','database'],['redis-server','database']];return specs.map(([name,type])=>[name,type,command(name)]).filter(x=>x[2]).map(([name,type,bin])=>candidate({type,key:`binary:${name}`,name,source:'path',confidence:1,reasons:['executable available'],meta:{binary:bin},defaultEnabled:type!=='database'}))}
function scanPm2(){const items=[];const bin=command('pm2');if(!bin)return items;try{const raw=execFileSync(bin,['jlist'],{encoding:'utf8',timeout:6000,maxBuffer:4*1024*1024}),start=raw.indexOf('['),list=JSON.parse(raw.slice(start));for(const proc of list){const name=proc.name||String(proc.pm_id),cwd=proc.pm2_env?.pm_cwd||null;items.push(candidate({type:'service',key:`pm2:${name}`,name,source:'pm2',confidence:.97,reasons:['PM2 process inventory'],meta:{status:proc.pm2_env?.status,cwd}}));if(cwd&&exists(path.join(cwd,'.git')))items.push(candidate({type:'project',key:cwd,name:path.basename(cwd),path:cwd,source:'pm2',confidence:.92,reasons:['PM2 working directory','git repository']}))}}catch{}return items}

function scanDocker(){const items=[];if(!command('docker'))return items;try{const out=execFileSync('docker',['ps','-a','--format','{{json .}}'],{encoding:'utf8',timeout:8000,maxBuffer:4*1024*1024});for(const line of out.split('\n').filter(Boolean)){let row;try{row=JSON.parse(line)}catch{continue}const project=row.Labels?.match(/com\.docker\.compose\.project=([^,]+)/)?.[1]||null;items.push(candidate({type:'container',key:row.ID||row.Names,name:row.Names||row.ID,source:'docker',confidence:.99,reasons:['Docker daemon inventory'],meta:{image:row.Image,status:row.Status,project}}));if(project)items.push(candidate({type:'project',key:`compose:${project}`,name:project,source:'docker-compose',confidence:.94,reasons:['Docker Compose labels'],meta:{composeProject:project}}))}}catch{}return items}
export function discoverHost({roots=parseRoots(process.env.DISCOVERY_ROOTS)}={}){const tree=scanTree(roots),items=mergeCandidates([...tree.items,...scanNginx(),...scanSystemd(),...scanCapabilities(),...scanPm2(),...scanDocker()]);return{schema:DISCOVERY_SCHEMA,generatedAt:Date.now(),host:{hostname:process.env.HOSTNAME||'unknown',platform:process.platform,arch:process.arch},roots,summary:Object.fromEntries([...new Set(items.map(x=>x.type))].map(type=>[type,items.filter(x=>x.type===type).length])),items,suggested:{deployDirs:tree.gitRoots,backupDirs:tree.backupRoots},diagnostics:{itemCount:items.length}}}
