import fs from 'node:fs';import path from 'node:path';import {config} from '../config.js';
export const discoveryPath=path.join(config.stateDir,'discovery.json');
export const discoverySettingsPath=path.join(config.stateDir,'discovery-settings.json');
const defaults=()=>({version:2,updatedAt:null,completedAt:null,enabledIds:[],disabledIds:[],roots:[],preferences:{autoEnableConfidence:.75,monitorNewHighConfidence:true}});
export function readDiscovery(){try{return JSON.parse(fs.readFileSync(discoveryPath,'utf8'))}catch{return{schema:1,generatedAt:null,summary:{},items:[],suggested:{deployDirs:[],backupDirs:[]},diagnostics:{unavailable:true}}}}
export function readDiscoverySettings(){try{const raw=JSON.parse(fs.readFileSync(discoverySettingsPath,'utf8')),next={...defaults(),...raw,preferences:{...defaults().preferences,...raw.preferences}};if(Number(raw.version||1)<2&&next.enabledIds.length>50&&next.disabledIds.length===0){next.enabledIds=[];next.version=2}return next}catch{return defaults()}}
export function writeDiscoverySettings(input={}){const snapshot=readDiscovery(),known=new Set(snapshot.items.map(x=>x.id)),cleanIds=value=>[...new Set((Array.isArray(value)?value:[]).map(String).filter(x=>known.has(x)))];const roots=[...new Set((Array.isArray(input.roots)?input.roots:[]).map(String).filter(x=>x.startsWith('/')&&!x.includes('\0')).slice(0,20))];const current=readDiscoverySettings(),next={...current,version:2,updatedAt:Date.now(),enabledIds:cleanIds(input.enabledIds),disabledIds:cleanIds(input.disabledIds),roots,preferences:{autoEnableConfidence:Math.max(.5,Math.min(1,Number(input.preferences?.autoEnableConfidence??current.preferences.autoEnableConfidence))),monitorNewHighConfidence:Boolean(input.preferences?.monitorNewHighConfidence??current.preferences.monitorNewHighConfidence)}};if(input.complete)next.completedAt=current.completedAt||Date.now();const tmp=`${discoverySettingsPath}.tmp`;fs.writeFileSync(tmp,JSON.stringify(next,null,2),{mode:0o600});fs.renameSync(tmp,discoverySettingsPath);return next}
export function resolvedDiscovery(){const snapshot=readDiscovery(),settings=readDiscoverySettings(),enabled=new Set(settings.enabledIds),disabled=new Set(settings.disabledIds),threshold=settings.preferences.autoEnableConfidence;const items=snapshot.items.map(item=>({...item,enabled:enabled.has(item.id)||(!disabled.has(item.id)&&item.defaultEnabled&&item.confidence>=threshold),selection:enabled.has(item.id)?'manual-on':disabled.has(item.id)?'manual-off':'automatic'}));return{...snapshot,items,settings}}
export function selectedPaths(type){return resolvedDiscovery().items.filter(x=>x.type===type&&x.enabled&&x.path).map(x=>x.path)}

export function enabledTargets(type){const resolved=resolvedDiscovery();if(!resolved.settings.completedAt)return null;return resolved.items.filter(x=>x.type===type&&x.enabled)}
export function enabledNames(type,source){const items=enabledTargets(type);return items?new Set(items.filter(x=>!source||x.source===source).map(x=>x.name)):null}
