import { config } from '../config.js';
import { initDatabase } from './connection.js';
const RANGE={"1h":{ms:3600_000,bucket:30},"24h":{ms:86400_000,bucket:300},"7d":{ms:604800_000,bucket:1800},"30d":{ms:2592000_000,bucket:7200}};
function ensure(){initDatabase().exec(`CREATE TABLE IF NOT EXISTS fleet_nodes(node_id TEXT PRIMARY KEY,name TEXT NOT NULL,public_url TEXT,version TEXT,first_seen INTEGER NOT NULL,last_seen INTEGER NOT NULL,snapshot_json TEXT NOT NULL);CREATE TABLE IF NOT EXISTS fleet_metrics(node_id TEXT NOT NULL,ts INTEGER NOT NULL,cpu REAL DEFAULT 0,memory REAL DEFAULT 0,swap REAL DEFAULT 0,load1 REAL DEFAULT 0,disk_used REAL DEFAULT 0,network_rx REAL DEFAULT 0,network_tx REAL DEFAULT 0,alert_count INTEGER DEFAULT 0,critical_count INTEGER DEFAULT 0,PRIMARY KEY(node_id,ts));CREATE INDEX IF NOT EXISTS idx_fleet_metrics_node_ts ON fleet_metrics(node_id,ts)`)}
const n=v=>Number.isFinite(Number(v))?Number(v):0;
export function ingestFleetSnapshot(id,p){ensure();const db=initDatabase(),now=Date.now(),s=p.snapshot||{},node=p.node||{},root=(s.filesystems||[]).find(x=>x.mount==='/')||{},alerts=s.alerts||[],json=JSON.stringify(p);if(Buffer.byteLength(json)>2097152)throw Error('snapshot_too_large');db.transaction(()=>{db.prepare(`INSERT INTO fleet_nodes VALUES(?,?,?,?,?,?,?) ON CONFLICT(node_id) DO UPDATE SET name=excluded.name,public_url=excluded.public_url,version=excluded.version,last_seen=excluded.last_seen,snapshot_json=excluded.snapshot_json`).run(id,String(node.name||id).slice(0,100),String(node.publicUrl||'').slice(0,300),String(node.version||'').slice(0,40),now,now,json);db.prepare(`INSERT OR REPLACE INTO fleet_metrics VALUES(?,?,?,?,?,?,?,?,?,?,?)`).run(id,now,n(s.cpu?.usage),n(s.memory?.usedPct),n(s.memory?.swapPct),n(s.load?.one),n(root.usedPct),n(s.network?.rxRate),n(s.network?.txRate),alerts.length,alerts.filter(a=>a.level==='critical').length)})();db.prepare('DELETE FROM fleet_metrics WHERE ts<?').run(now-config.historyRetentionDays*86400_000)}
export function listFleetNodes(offline=45000){ensure();const now=Date.now();return initDatabase().prepare('SELECT * FROM fleet_nodes ORDER BY name').all().map(r=>{let p={};try{p=JSON.parse(r.snapshot_json)}catch{}const s=p.snapshot||{},root=(s.filesystems||[]).find(x=>x.mount==='/')||{},a=s.alerts||[];return{id:r.node_id,name:r.name,publicUrl:r.public_url,version:r.version,lastSeen:r.last_seen,online:now-r.last_seen<=offline,cpu:n(s.cpu?.usage),memory:n(s.memory?.usedPct),disk:n(root.usedPct),alerts:a.length,critical:a.filter(x=>x.level==='critical').length,update:s.update||null}})}
export function fleetNodeSnapshot(id){ensure();const r=initDatabase().prepare('SELECT last_seen,snapshot_json FROM fleet_nodes WHERE node_id=?').get(id);if(!r)return null;try{return{receivedAt:r.last_seen,...JSON.parse(r.snapshot_json)}}catch{return null}}
export function fleetHistory(id,name='24h'){ensure();const r=RANGE[name]||RANGE['24h'],from=Date.now()-r.ms,b=r.bucket*1000,rows=initDatabase().prepare(`SELECT CAST(ts/? AS INTEGER)*? ts,ROUND(AVG(cpu),2) cpu,ROUND(AVG(memory),2) memory,ROUND(AVG(swap),2) swap,ROUND(AVG(load1),2) load1,ROUND(MAX(disk_used),2) disk_used,ROUND(AVG(network_rx),2) network_rx,ROUND(AVG(network_tx),2) network_tx,MAX(alert_count) alert_count,MAX(critical_count) critical_count FROM fleet_metrics WHERE node_id=? AND ts>=? GROUP BY CAST(ts/? AS INTEGER) ORDER BY ts`).all(b,b,id,from,b);return{nodeId:id,range:RANGE[name]?name:'24h',bucketSeconds:r.bucket,from,to:Date.now(),rows}}
