#!/usr/bin/env bash
# VPS Sentinel installer. Idempotent: safe to re-run.
set -euo pipefail

APP_DIR=/opt/vps-sentinel
STATE_DIR=/var/lib/vps-sentinel
DOMAIN="${DOMAIN:-vps.grouvi.online}"
SVC_USER=vpssentinel
SNIP=/etc/nginx/snippets

say() { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }
ok()  { printf '    \033[0;32mok\033[0m %s\n' "$*"; }

[ "$(id -u)" -eq 0 ] || { echo 'run as root'; exit 1; }

# ---------------------------------------------------------------- user
say "Service account"
if ! id "$SVC_USER" >/dev/null 2>&1; then
  useradd --system --no-create-home --shell /usr/sbin/nologin "$SVC_USER"
  ok "created $SVC_USER"
else
  ok "$SVC_USER exists"
fi
for g in docker adm; do
  getent group "$g" >/dev/null && usermod -aG "$g" "$SVC_USER"
done
ok "groups: $(id -nG "$SVC_USER")"

# --------------------------------------------------------------- state
say "State directory"
install -d -m 700 -o "$SVC_USER" -g "$SVC_USER" "$STATE_DIR"
ok "$STATE_DIR"

# ------------------------------------------------------------ app deps
say "Dependencies"
cd "$APP_DIR"
npm ci --omit=dev --no-audit --no-fund 2>&1 | tail -3
chown -R root:root "$APP_DIR"
chmod -R go-w "$APP_DIR"
ok "node_modules ready"

# -------------------------------------------------------------- sudoers
say "Sudo rules (2 read-only commands)"
install -m 440 -o root -g root deploy/sudoers-vps-sentinel /etc/sudoers.d/vps-sentinel
visudo -cf /etc/sudoers.d/vps-sentinel >/dev/null
ok "validated"

# ----------------------------------------------------------- cloudflare
say "Cloudflare IP ranges"
mkdir -p "$SNIP"
TMP4=$(mktemp); TMP6=$(mktemp)
curl -fsS --max-time 20 https://www.cloudflare.com/ips-v4 -o "$TMP4" || true
curl -fsS --max-time 20 https://www.cloudflare.com/ips-v6 -o "$TMP6" || true
if [ -s "$TMP4" ]; then
  {
    echo '# generated by vps-sentinel installer'
    while read -r n; do [ -n "$n" ] && echo "set_real_ip_from $n;"; done < "$TMP4"
    while read -r n; do [ -n "$n" ] && echo "set_real_ip_from $n;"; done < "$TMP6"
    echo 'real_ip_header CF-Connecting-IP;'
    echo 'real_ip_recursive on;'
  } > "$SNIP/cloudflare-realip.conf"
  {
    echo '# generated by vps-sentinel installer'
    while read -r n; do [ -n "$n" ] && echo "allow $n;"; done < "$TMP4"
    while read -r n; do [ -n "$n" ] && echo "allow $n;"; done < "$TMP6"
    echo 'allow 127.0.0.1;'
  } > "$SNIP/cloudflare-allow.conf"
  ok "$(grep -c set_real_ip_from "$SNIP/cloudflare-realip.conf") ranges"
else
  echo 'real_ip_header CF-Connecting-IP;' > "$SNIP/cloudflare-realip.conf"
  echo 'allow all;' > "$SNIP/cloudflare-allow.conf"
  echo '    !! could not fetch Cloudflare ranges, origin left open'
fi
rm -f "$TMP4" "$TMP6"
install -m 644 deploy/sentinel-proxy.conf "$SNIP/sentinel-proxy.conf"

# --------------------------------------------------------------- certs
say "TLS certificate for $DOMAIN"
if [ ! -d "/etc/letsencrypt/live/$DOMAIN" ]; then
  mkdir -p /var/www/html
  cat > /etc/nginx/sites-available/vps-sentinel-bootstrap <<EOF
server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN;
    location /.well-known/acme-challenge/ { root /var/www/html; }
    location / { return 404; }
}
EOF
  ln -sf /etc/nginx/sites-available/vps-sentinel-bootstrap /etc/nginx/sites-enabled/vps-sentinel-bootstrap
  nginx -t && systemctl reload nginx
  certbot certonly --webroot -w /var/www/html -d "$DOMAIN" \
    --non-interactive --agree-tos --register-unsafely-without-email --keep-until-expiring
  rm -f /etc/nginx/sites-enabled/vps-sentinel-bootstrap
  ok "certificate issued"
else
  ok "certificate already present"
fi

# --------------------------------------------------------------- nginx
say "nginx vhost"
sed "s/vps\\.grouvi\\.online/$DOMAIN/g" deploy/nginx-vps-sentinel.conf \
  > /etc/nginx/sites-available/vps-sentinel
ln -sf /etc/nginx/sites-available/vps-sentinel /etc/nginx/sites-enabled/vps-sentinel
nginx -t
ok "config valid"

# ------------------------------------------------------------- service
say "systemd service"
if [ ! -f /etc/vps-sentinel.env ]; then
  cat > /etc/vps-sentinel.env <<EOF
NODE_ENV=production
PORT=3999
HOST=127.0.0.1
RP_ID=$DOMAIN
ORIGIN=https://$DOMAIN
RP_NAME=VPS Sentinel
STATE_DIR=$STATE_DIR
BACKUP_DIRS=/opt/coursebot/backups,/opt/mmo90s/backups,/opt/reip/backups
EOF
  chmod 640 /etc/vps-sentinel.env
  ok "/etc/vps-sentinel.env created"
fi
install -m 644 deploy/vps-sentinel.service /etc/systemd/system/vps-sentinel.service
systemctl daemon-reload
systemctl enable --now vps-sentinel
sleep 2
systemctl reload nginx

say "Status"
systemctl is-active vps-sentinel && ok 'vps-sentinel running'
curl -fsS --max-time 5 http://127.0.0.1:3999/healthz && echo
say "Next: create your passkey"
echo "    cd $APP_DIR && npm run enroll"
echo "    cd $APP_DIR && npm run recovery   # backup codes"
echo
