#!/usr/bin/env bash
# VPS Sentinel installer. Idempotent: safe to re-run.
set -euo pipefail

APP_DIR=/opt/vps-sentinel
STATE_DIR=/var/lib/vps-sentinel
DOMAIN="${DOMAIN:-vps.grouvi.online}"
SVC_USER=vpssentinel
SNIP=/etc/nginx/snippets
BACKUP_DIRS="${BACKUP_DIRS:-/opt/coursebot/backups,/opt/mmo90s/backups,/opt/reip/backups}"

say() { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }
ok()  { printf '    \033[0;32mok\033[0m %s\n' "$*"; }

[ "$(id -u)" -eq 0 ] || { echo 'run as root'; exit 1; }

# ---------------------------------------------------------------- user
say "Service account"
if ! id "$SVC_USER" >/dev/null 2>&1; then
  useradd --system --no-create-home --shell /usr/sbin/nologin "$SVC_USER"
  ok "created $SVC_USER"
else
  ok "$SVC_USER exists"
fi
for g in docker adm; do
  getent group "$g" >/dev/null && usermod -aG "$g" "$SVC_USER"
done
ok "groups: $(id -nG "$SVC_USER")"

# --------------------------------------------------------------- state
say "State directory"
install -d -m 700 -o "$SVC_USER" -g "$SVC_USER" "$STATE_DIR"
ok "$STATE_DIR"

# ------------------------------------------------------------ app deps
say "Dependencies"
cd "$APP_DIR"
if [ -f package-lock.json ]; then
  npm ci --omit=dev --no-audit --no-fund 2>&1 | tail -3
else
  npm install --omit=dev --no-audit --no-fund 2>&1 | tail -3
fi
chown -R root:root "$APP_DIR"
chmod -R go-w "$APP_DIR"
ok "node_modules ready"

# ------------------------------------------------- drop legacy sudoers
if [ -f /etc/sudoers.d/vps-sentinel ]; then
  say "Removing legacy sudo rules"
  rm -f /etc/sudoers.d/vps-sentinel
  ok "web process now has no escalation path at all"
fi

# --------------------------------------------------- backup dir access
say "Read access to backup directories"
if command -v setfacl >/dev/null 2>&1; then
  IFS=',' read -ra DIRS <<< "$BACKUP_DIRS"
  for d in "${DIRS[@]}"; do
    d=$(echo "$d" | xargs)
    [ -d "$d" ] || { echo "    -- $d does not exist, skipped"; continue; }
    parent=$(dirname "$d")
    setfacl -m "u:$SVC_USER:x"  "$parent" 2>/dev/null || true
    setfacl -m "u:$SVC_USER:rx" "$d"      2>/dev/null || true
    if sudo -u "$SVC_USER" test -r "$d"; then ok "$d readable"; else echo "    !! $d still unreadable"; fi
  done
else
  echo '    !! setfacl not installed (apt install acl) - backup panel may be empty'
fi

# ----------------------------------------------------------- cloudflare
say "Cloudflare IP ranges"
mkdir -p "$SNIP"
TMP4=$(mktemp); TMP6=$(mktemp)
curl -fsS --max-time 20 https://www.cloudflare.com/ips-v4 -o "$TMP4" || true
curl -fsS --max-time 20 https://www.cloudflare.com/ips-v6 -o "$TMP6" || true
if [ -s "$TMP4" ]; then
  {
    echo '# generated by vps-sentinel installer'
    while read -r n; do [ -n "$n" ] && echo "set_real_ip_from $n;"; done < "$TMP4"
    while read -r n; do [ -n "$n" ] && echo "set_real_ip_from $n;"; done < "$TMP6"
    echo 'real_ip_header CF-Connecting-IP;'
    echo 'real_ip_recursive on;'
  } > "$SNIP/cloudflare-realip.conf"
  {
    echo '# generated by vps-sentinel installer'
    while read -r n; do [ -n "$n" ] && echo "allow $n;"; done < "$TMP4"
    while read -r n; do [ -n "$n" ] && echo "allow $n;"; done < "$TMP6"
    echo 'allow 127.0.0.1;'
  } > "$SNIP/cloudflare-allow.conf"
  ok "$(grep -c set_real_ip_from "$SNIP/cloudflare-realip.conf") ranges"
else
  echo 'real_ip_header CF-Connecting-IP;' > "$SNIP/cloudflare-realip.conf"
  echo 'allow all;' > "$SNIP/cloudflare-allow.conf"
  echo '    !! could not fetch Cloudflare ranges, origin left open'
fi
rm -f "$TMP4" "$TMP6"
install -m 644 deploy/sentinel-proxy.conf "$SNIP/sentinel-proxy.conf"

# --------------------------------------------------------------- certs
say "TLS certificate for $DOMAIN"
if [ ! -d "/etc/letsencrypt/live/$DOMAIN" ]; then
  mkdir -p /var/www/html
  cat > /etc/nginx/sites-available/vps-sentinel-bootstrap <<EOF
server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN;
    location /.well-known/acme-challenge/ { root /var/www/html; }
    location / { return 404; }
}
EOF
  ln -sf /etc/nginx/sites-available/vps-sentinel-bootstrap /etc/nginx/sites-enabled/vps-sentinel-bootstrap
  nginx -t && systemctl reload nginx
  certbot certonly --webroot -w /var/www/html -d "$DOMAIN" \
    --non-interactive --agree-tos --register-unsafely-without-email --keep-until-expiring
  rm -f /etc/nginx/sites-enabled/vps-sentinel-bootstrap
  ok "certificate issued"
else
  ok "certificate already present"
fi

# --------------------------------------------------------------- nginx
say "nginx vhost"
sed "s/vps\\.grouvi\\.online/$DOMAIN/g" deploy/nginx-vps-sentinel.conf \
  > /etc/nginx/sites-available/vps-sentinel

# nginx >= 1.25.1 uses the standalone "http2 on;" directive, older ones the listen flag
NGX_VER=$(nginx -v 2>&1 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1)
NGX_MAJOR=${NGX_VER%%.*}
NGX_MINOR=$(echo "$NGX_VER" | cut -d. -f2)
if [ "$NGX_MAJOR" -lt 1 ] || { [ "$NGX_MAJOR" -eq 1 ] && [ "$NGX_MINOR" -lt 25 ]; }; then
  sed -i '/^    http2 on;$/d' /etc/nginx/sites-available/vps-sentinel
  sed -i 's/^    listen 443 ssl;$/    listen 443 ssl http2;/' /etc/nginx/sites-available/vps-sentinel
  ok "nginx $NGX_VER - legacy http2 syntax"
else
  ok "nginx $NGX_VER - modern http2 directive"
fi

ln -sf /etc/nginx/sites-available/vps-sentinel /etc/nginx/sites-enabled/vps-sentinel
nginx -t
ok "config valid"

# ------------------------------------------------------------- service
say "systemd service"
if [ ! -f /etc/vps-sentinel.env ]; then
  cat > /etc/vps-sentinel.env <<EOF
NODE_ENV=production
PORT=3999
HOST=127.0.0.1
RP_ID=$DOMAIN
ORIGIN=https://$DOMAIN
RP_NAME=VPS Sentinel
STATE_DIR=$STATE_DIR
BACKUP_DIRS=$BACKUP_DIRS
EOF
  chmod 640 /etc/vps-sentinel.env
  ok "/etc/vps-sentinel.env created"
fi
install -m 644 deploy/vps-sentinel-agent.service /etc/systemd/system/vps-sentinel-agent.service
install -m 644 deploy/vps-sentinel.service /etc/systemd/system/vps-sentinel.service
systemctl daemon-reload
systemctl enable vps-sentinel-agent vps-sentinel >/dev/null 2>&1 || true
systemctl restart vps-sentinel-agent
sleep 2
systemctl restart vps-sentinel
sleep 3
systemctl reload nginx

say "Status"
systemctl is-active vps-sentinel-agent && ok 'privileged collector running'
systemctl is-active vps-sentinel && ok 'dashboard running'
curl -fsS --max-time 5 http://127.0.0.1:3999/healthz && echo
say "Next: create your passkey"
echo "    cd $APP_DIR && npm run enroll"
echo "    cd $APP_DIR && npm run recovery   # backup codes"
echo
