import assert from 'node:assert/strict';
import fs from 'node:fs';
import http from 'node:http';
import { chromium } from 'playwright';
import { createApp } from '../../src/app.js';
import {discoveryPath,writeDiscoverySettings} from '../../src/discovery/store.js';
import {candidate} from '../../src/discovery/model.js';
import {ingestFleetSnapshot} from '../../src/database.js';

const fixture=candidate({type:'project',key:'/srv/example',name:'example',path:'/srv/example',source:'fixture',confidence:.95,reasons:['git repository']});fs.mkdirSync(process.env.STATE_DIR,{recursive:true});fs.writeFileSync(discoveryPath,JSON.stringify({schema:1,generatedAt:Date.now(),summary:{project:1},items:[fixture],suggested:{},diagnostics:{itemCount:1}}));writeDiscoverySettings({complete:true,enabledIds:[fixture.id]});
ingestFleetSnapshot('test-node',{schema:1,node:{id:'test-node',name:'Test Node',publicUrl:'https://node.example',version:'1.24.6'},snapshot:{startedAt:Date.now()-60000,uptime:60,kernel:{hostname:'remote-host'},os:{pretty:'Ubuntu Test'},cpu:{usage:21,count:2,cores:[20,22],iowait:0,steal:0,procsRunning:2,procsBlocked:0},memory:{usedPct:42,total:1024**3,used:440*1024**2,available:584*1024**2,swapPct:0,swapUsed:0,swapTotal:0},load:{one:.2,five:.25,fifteen:.3,processes:80},network:{rxRate:1024,txRate:512,rxTotal:1024,txTotal:512,errors:0},diskIo:{readRate:4096,writeRate:8192},filesystems:[{mount:'/',device:'/dev/vda1',size:10e9,used:4e9,avail:6e9,usedPct:40}],history:{at:[Date.now()],cpu:[21],mem:[42],swap:[0],load:[.2],rx:[1],tx:[.5],ioR:[0],ioW:[0]},containers:{available:true,items:[],running:0,stopped:0,unhealthy:0},pm2:{available:false,items:[],down:0},systemd:{failedUnits:[],nginx:'active',docker:'active',ssh:'active'},alerts:[],update:{current:'1.24.6',latest:'1.24.6',available:false}},safe:{filesystem:{at:Date.now(),totals:{files:12,directories:4,symlinks:1,bytes:1048576},types:[{name:'Code',bytes:786432,files:8},{name:'Data',bytes:262144,files:4}]},projects:{summary:{projects:1,linked:2,runtimes:1,unassigned:0},items:[{id:'safe-project',name:'Safe Project',stack:['container'],health:{runtimeCount:1,running:1,attention:0,componentCount:2}}]},deployments:[{project:'safe-project',branch:'main',dirty:false,dirtyCount:0,ahead:0,behind:0,commits:[{short:'abc1234',at:new Date().toISOString(),subject:'Sanitized commit'}]}]}});
const app=createApp({sessionResolver:()=>({sid:'visual'}),apiAuth:(req,res,next)=>{req.session={sid:'visual',exp:Date.now()+3600000};next()}});
const server=http.createServer(app);await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const base=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH||undefined});
async function pageAt(width=1440,height=900){const context=await browser.newContext({viewport:{width,height}});const page=await context.newPage();const errors=[];page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>{if(message.type()==='error'&&message.text().includes('Content Security Policy'))errors.push(message.text())});await page.goto(base,{waitUntil:'networkidle'});await page.waitForTimeout(350);assert.deepEqual(errors,[]);assert.ok(!(await page.locator('#incidentList').textContent()).includes('Ошибка загрузки'));return{page,context}}
try {
  const {page,context}=await pageAt();
  const chrome=await page.evaluate(()=>['.topbar','.forge-pane-head','.notify-pane-head','.detail-head'].map(selector=>document.querySelector(selector).getBoundingClientRect().height));
  assert.deepEqual(chrome,[56,56,56,56]);
  const uiText=await page.locator('body').innerText();assert.doesNotMatch(uiText,/\?{3,}/,'UI must not contain replacement question marks');
  assert.equal(await page.locator('#fleetSelect option').count(),2,'hub must offer local and remote data sources');const navCount=await page.locator('a.nav-item').count();await page.selectOption('#fleetSelect','test-node');await page.waitForTimeout(250);assert.equal(await page.locator('#tbTitle').textContent(),'remote-host');assert.match(await page.locator('#netVal').textContent(),/КБ|Б/,'remote network KPI must redraw immediately');assert.match(await page.locator('#ioFoot').textContent(),/4\.0 КБ\/с|8\.0 КБ\/с/,'remote disk IO must redraw immediately');assert.notEqual(await page.locator('#storageTotal').textContent(),'—','sanitized storage diagram must render for remote node');assert.match(await page.locator('#projectList').textContent(),/Safe Project/);assert.match(await page.locator('#deployments').textContent(),/Sanitized commit/);assert.equal(await page.locator('#fsSearch').isDisabled(),true,'local-only controls must be disabled for remote node');assert.equal(await page.locator('a.nav-item').count(),navCount,'node switching must not mutate sidebar navigation');assert.equal(await page.locator('#s-incidents').isVisible(),true,'all dashboard sections stay in the shared DOM');await page.locator('#s-incidents').evaluate(x=>x.scrollIntoView({block:'start'}));await page.waitForTimeout(180);assert.equal(await page.locator('a.nav-item[href="#s-incidents"]').evaluate(x=>x.classList.contains('active')),true,'scroll spy must survive node switching');await page.selectOption('#fleetSelect','local');await page.waitForTimeout(250);assert.equal(await page.locator('a.nav-item').count(),navCount);assert.equal(await page.locator('#fsSearch').isDisabled(),false);assert.notEqual(await page.locator('#tbTitle').textContent(),'remote-host');
  assert.equal(await page.locator('#updateOpen svg path').first().getAttribute('d'),'M12 3v12M7 10l5 5 5-5','update action must use the download icon');
  await page.locator('#updateOpen').evaluate(button=>{button.hidden=false});const actionSizes=await page.locator('#updateOpen,#logout').evaluateAll(items=>items.map(x=>{const r=x.getBoundingClientRect();return[Math.round(r.width),Math.round(r.height)]}));assert.deepEqual(actionSizes[0],actionSizes[1],'update action must match logout geometry');await page.click('#updateOpen');await page.waitForTimeout(180);assert.equal(await page.locator('#updatePane').evaluate(x=>x.classList.contains('open')),true,'update drawer must open from the app bar');await page.click('#updateClose');await page.waitForTimeout(180);assert.equal(await page.locator('#updatePane').evaluate(x=>x.classList.contains('open')),false);
  const kpis=await page.locator('.kpi').evaluateAll(items=>items.map(x=>Math.round(x.getBoundingClientRect().top)));
  assert.equal(new Set(kpis).size,1,'six KPI blocks must share one desktop row');assert.equal(await page.locator('#s-discovery').count(),1);assert.ok(await page.locator('.project-workspace').count()>0);await page.locator('[data-project-id]').first().click();await page.waitForTimeout(250);assert.equal(await page.locator('#detailPane').evaluate(x=>x.classList.contains('open')),true);assert.equal(await page.locator('#detailType').textContent(),'Project workspace');
  await page.goto(`${base}/setup`,{waitUntil:'networkidle'});assert.equal(await page.locator('.setup-app').count(),1);await page.click('#nextBtn');await page.click('#nextBtn');assert.equal(await page.locator('#confidenceSelect').count(),1);assert.equal(await page.locator('#monitorNew').count(),1);assert.ok(Number.parseFloat(await page.locator('.field>span').first().evaluate(x=>getComputedStyle(x).fontSize))>=9.5);await page.route('**/api/discovery/settings',route=>route.request().method()==='PUT'?route.fulfill({status:200,contentType:'application/json',body:'{"ok":true}'}):route.continue());await page.click('#nextBtn');assert.equal(await page.locator('#fleetHubUrl').isVisible(),false);await page.check('[name="fleetRole"][value="node"]');assert.equal(await page.locator('#fleetHubUrl').isVisible(),true);assert.equal(await page.locator('#fleetNodesJson').isVisible(),false);await page.click('#nextBtn');assert.match(await page.locator('#setupFeedback').textContent(),/Node ID|название|Hub URL|pairing/i);assert.equal(await page.locator('#fleetHubUrl').count(),1);await page.check('[name="fleetRole"][value="hub"]');assert.equal(await page.locator('#fleetHubUrl').isVisible(),false);await page.locator('.fleet-advanced summary').click();assert.equal(await page.locator('#fleetNodesJson').isVisible(),true);await page.goto(`${base}/settings`,{waitUntil:'networkidle'});await page.waitForTimeout(350);assert.equal(await page.locator('#settingsPane').evaluate(x=>x.classList.contains('open')),true);assert.equal(await page.locator('#settingsRail').evaluate(x=>x.classList.contains('open')),true);assert.equal(await page.locator('.drawer-settings-section').count(),6);await page.selectOption('#drawerFleetForm [name="role"]','node');assert.equal(await page.locator('#drawerFleetForm [name="hubUrl"]').isVisible(),true);assert.equal(await page.locator('#drawerFleetForm [name="nodesJson"]').isVisible(),false);await page.selectOption('#drawerFleetForm [name="role"]','standalone');assert.equal(await page.locator('#drawerFleetForm [name="nodeId"]').isVisible(),false);await page.locator('#drawer-ai').evaluate(x=>x.scrollIntoView({block:'start'}));await page.waitForTimeout(180);assert.equal(await page.locator('[data-settings-nav="ai"]').evaluate(x=>x.classList.contains('active')),true);await page.locator('#settingsDrawerContent').evaluate(x=>x.scrollTop=x.scrollHeight);await page.waitForTimeout(180);assert.equal(await page.locator('[data-settings-nav="security"]').evaluate(x=>x.classList.contains('active')),true);await page.click('#settingsClose');await page.waitForTimeout(380);assert.equal(await page.locator('#settingsPane').evaluate(x=>x.classList.contains('open')),false);assert.equal(await page.locator('#settingsRail').evaluate(x=>x.classList.contains('open')),false);await page.click('#forgeOpen');await page.waitForTimeout(420);
  assert.equal(await page.locator('#forgePane').evaluate(x=>x.classList.contains('open')),true);
  await context.close();

  const narrow=await pageAt(1280,900);await narrow.page.click('#forgeOpen');await narrow.page.evaluate(()=>{const pane=document.querySelector('#forgePane');pane.style.setProperty('--pane-width','640px');window.dispatchEvent(new Event('resize'))});await narrow.page.waitForTimeout(420);
  const geometry=await narrow.page.evaluate(()=>{const content=document.querySelector('.content');return{width:content.clientWidth,overflow:content.scrollWidth-content.clientWidth,headers:['#s-incidents','#s-filesystem','#s-ops'].map(s=>document.querySelector(s).getBoundingClientRect().width),pane:document.querySelector('#forgePane').getBoundingClientRect().width}});
  assert.equal(Math.round(geometry.pane),640);assert.ok(geometry.width>=400);assert.ok(geometry.overflow<=1,`workspace horizontal overflow ${geometry.overflow}`);assert.ok(geometry.headers.every(x=>x<=geometry.width));
  await narrow.context.close();
  console.log('visual layout contract: ok');
} finally {await browser.close();await new Promise(resolve=>server.close(resolve))}
