import { config } from './config.js';
import { getNotificationSettings, notificationDeliveryHealth, recordNotification } from './database.js';
import { investigateIncident } from './investigator.js';

const recentlySent=new Map();
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
function icon(severity,type){if(type==='resolved')return '✅';return severity==='critical'?'🔴':'🟠'}
function messageFor(event){const i=event.incident,status=event.type==='opened'?'Новый инцидент':event.type==='escalated'?'Инцидент ухудшился':'Инцидент закрыт',duration=i.resolved_at?Math.max(1,Math.round((i.resolved_at-i.first_seen)/60000)):null;return [`${icon(i.severity,event.type)} <b>${status}</b>`,`<b>${esc(i.title)}</b>`,i.detail?esc(i.detail):'',`Источник: <code>${esc(i.source)}</code>`,duration?`Длительность: ${duration} мин.`:'',i.investigation?`<b>AI-разбор</b>\n${esc(i.investigation).slice(0,1800)}`:'',`<a href="${config.origin}/#s-incidents">Открыть Grouvi Nox</a>`].filter(Boolean).join('\n')}
function quietNow(s){if(!s.quietEnabled||s.quietStart===s.quietEnd)return false;const hour=Number(new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Tomsk',hour:'2-digit',hourCycle:'h23'}).format(new Date()));return s.quietStart<s.quietEnd?hour>=s.quietStart&&hour<s.quietEnd:hour>=s.quietStart||hour<s.quietEnd}
export function telegramState(){const settings=getNotificationSettings();return{enabled:config.telegram.enabled&&settings.enabled,configured:Boolean(config.telegram.botToken&&config.telegram.chatId),chat:config.telegram.chatId?`…${config.telegram.chatId.slice(-4)}`:null,settings,delivery:notificationDeliveryHealth(),timezone:'Asia/Tomsk'}}
async function telegramAttempt(endpoint,text){const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:config.telegram.chatId,text:String(text).slice(0,4000),parse_mode:'HTML',disable_web_page_preview:true}),signal:AbortSignal.timeout(10000)});const body=await response.json().catch(()=>({}));if(!response.ok||!body.ok){const error=new Error(body.description||`HTTP ${response.status}`);error.status=response.status;error.retryAfter=Number(body.parameters?.retry_after||0);throw error}return body}
export async function sendTelegramText(text,{incidentId=null,eventType='report'}={}){
  if(!config.telegram.enabled)return{skipped:true,reason:'not_configured'};
  const endpoint=`https://api.telegram.org/bot${config.telegram.botToken}/sendMessage`;let lastError;
  for(let attempt=1;attempt<=3;attempt+=1){try{await telegramAttempt(endpoint,text);recordNotification({incidentId,eventType,success:true,detail:attempt>1?`sent_after_retry_${attempt}`:'sent'});return{sent:true,attempts:attempt}}catch(error){lastError=error;const retryable=!error.status||error.status===429||error.status>=500;if(!retryable||attempt===3)break;await sleep(error.retryAfter?error.retryAfter*1000:250*2**(attempt-1))}}
  recordNotification({incidentId,eventType,success:false,detail:lastError?.message||'unknown_error'});console.error('[telegram]',lastError?.message||'unknown_error');return{sent:false,error:lastError?.message||'unknown_error'};
}
export async function notifyIncident(event){if(!config.telegram.enabled)return{skipped:true,reason:'not_configured'};const s=getNotificationSettings(),severity=event.incident.severity;if(!s.enabled||!s[severity]||!s[event.type])return{skipped:true,reason:'filtered'};if(quietNow(s)&&!(severity==='critical'&&s.criticalDuringQuiet))return{skipped:true,reason:'quiet_hours'};const key=`${event.type}:${event.incident.id}:${severity}`,last=recentlySent.get(key)||0;if(Date.now()-last<s.cooldownMin*60000)return{skipped:true,reason:'deduplicated'};const result=await sendTelegramText(messageFor(event),{incidentId:event.incident.id,eventType:event.type});if(result.sent)recentlySent.set(key,Date.now());return result}
export async function notifyEvents(events){for(const event of events){if(event.incident.severity==='critical'&&['opened','escalated'].includes(event.type))event.incident=await investigateIncident(event.incident);await notifyIncident(event)}}
